services:
  - type: web
    name: pac-man-royal
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: ADMIN_USERNAMES
        value: S90LSY
